module.exports = {
"Address": require('./Address').default,
"Counters": require('./Counters').default,
"ERC165": require('./ERC165').default,
"IERC20": require('./IERC20').default,
"IERC165": require('./IERC165').default,
"IERC721": require('./IERC721').default,
"IERC721Receiver": require('./IERC721Receiver').default,
"SafeMath": require('./SafeMath').default,
"IERC721Enumerable": require('./IERC721Enumerable').default,
"IERC721Metadata": require('./IERC721Metadata').default,
"IERC721Full": require('./IERC721Full').default,
"ERC20": require('./ERC20').default,
"ERC20Burnable": require('./ERC20Burnable').default,
"RhodeIT": require('./RhodeIT').default,
"ERC721": require('./ERC721').default,
"ERC721Enumerable": require('./ERC721Enumerable').default,
"ERC721Metadata": require('./ERC721Metadata').default,
"ERC721Full": require('./ERC721Full').default,
"CryptoWorldWar": require('./CryptoWorldWar').default,
"ERC20Detailed": require('./ERC20Detailed').default,

};